### PR TITLE
format all rust code files

### PR DESCRIPTION
**Pull request by loannaflip**

### CODE REVIEW

**Comment by loannaflip** [comment]
Executed: `cargo fix` & `cargo fmt` (wrapper for `rustfmt`)

**Comment by Kreyren** [comment]
i ain't upstream for this project

**Comment by loannaflip** [comment]
@Kreyren You could maintain a better personal fork

**Comment by Kreyren** [comment]
Possibly, still considering unless @SUStudent decides to continues maintenance

**Pull request closed without merging**
